services:
  - type: web
    name: friday-jarvis
    runtime: python311
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LIVEKIT_URL
        value: wss://friday-uk2toy5r.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APIYnzgriSNVjbG
      - key: LIVEKIT_API_SECRET
        value: 0nICJFFHqmYECGsZ31pUR3EE98KUxaUbPlfPC4IFirX
      - key: GOOGLE_API_KEY
        value: AIzaSyAl7yKW8S26O9hv5PSVeeNOEBv90Cpzu7Y
      - key: GMAIL_APP_PASSWORD
        value: gnslnffozasyyppi
      - key: GMAIL_USER
        value: paullincoln428@gmail.com
    plan: free
